namespace Core.Entities
{
  public class BaseEntity
  {
    // By convention, 'Id' field will be used as the primary key of the table 'Products'
    // * autogenerated 
    public int Id { get; set; }
  }
}