namespace API.Entities
{
  public class Product
  {
    // By convention, 'Id' field will be used as the primary key of the table 'Products'
    // * autogenerated 
    public int Id { get; set; }
    public string Name { get; set; }
  }
}